Feature/add grpc
Ilhasoft/rapidpro-apps pull request #11
Opened 2021-02-23 18:32 UTC by Sandro-Meireles

Proto file PR: Ilhasoft/rapidpro-apps-protobuffers#1

2021-02-24 00:10 UTC, matmsa27 requested changes
Great work Sandro, congrats, I believe that is missing the `black` on the code to follow the Rapidpro conventions. Thanks 💯

2021-02-24 00:10 UTC, matmsa27 commented on weni/org_grpc/serializers.py
> +        fields = ["id", "user_id", "name", "timezone", "date_format", "plan",
ran `black` here?

2021-02-24 00:10 UTC, matmsa27 commented on weni/org_grpc/urls.py
> +    org_pb2_grpc.add_OrgControllerServicer_to_server(OrgService.as_servicer(), server)
please, add the newline at end of the file

2021-02-24 13:44 UTC, Sandro-Meireles commented on weni/org_grpc/serializers.py
> +        fields = ["id", "user_id", "name", "timezone", "date_format", "plan",
black was runned and I pushed a new commit: https://github.com/Ilhasoft/rapidpro-apps/pull/11/commits/b55eab767899e1ad7db8ead2b91eda78cc05a361

2021-02-24 13:46 UTC, Sandro-Meireles commented on weni/org_grpc/urls.py
> +    org_pb2_grpc.add_OrgControllerServicer_to_server(OrgService.as_servicer(), server)
I made the change and pushed on a new commit: https://github.com/Ilhasoft/rapidpro-apps/commit/b55eab767899e1ad7db8ead2b91eda78cc05a361

2021-02-24 14:05 UTC, matmsa27 approved these changes

2021-02-25 14:19 UTC, jcbalmeida reviewed
It would be nice to have a README with instructions on how to configure the app and run the server.
The required libraries can be added as requirements in setup.py too.

2021-02-25 14:39 UTC, jcbalmeida approved these changes

2021-02-25 14:43 UTC, jcbalmeida commented
We will make some improvements in the next PR, good job!

2021-02-25 14:43 UTC, merged