Feature/contatc analytics
Ilhasoft/rapidpro-apps pull request #2
Opened 2020-12-16 14:06 UTC by PeterAlexandre

2020-12-16 15:42 UTC, matmsa27 reviewed
Remover os arquivos .pyc, eles nao sao commitados.

2020-12-16 15:42 UTC, matmsa27 commented on analytics_api/README.md
> +**settings.py**
talvez seja interessante montar um script para adicionar essas configuracoes no settings.

2020-12-16 15:42 UTC, matmsa27 commented on analytics_api/README.md
> +from .settings_common import *
normalmente o settings.py ja herda tudo de `.settings_common.py`

2020-12-16 15:43 UTC, matmsa27 commented on analytics_api/apps.py
> +    name = 'apps.analytics_api'
rodou o black? o padrao dos projetos do rapidpro utiliza " no lugar de '

2020-12-16 15:44 UTC, matmsa27 commented on analytics_api/tests.py
> +# Create your tests here.
é interessante desenvolver testes, como você vai passar confiança do código da sua API para outro dev se ela não está coberta com testes.

2020-12-16 15:46 UTC, matmsa27 commented on analytics_api/README.md
> +# RapidPro Apps: Analytics API
Não precisa colocar as urls da sua api na url principal do Rapidpro também não?

2020-12-16 15:50 UTC, matmsa27 commented on analytics_api/views.py
> +        total_and_current_contacts = Contact.objects.aggregate(
Ja testou isso com uma grande quantidade de contatos? Como o RP e Push possui bancos extremamente gigantes, talvez isso demore um pouco, e ai seja interessante validar se dessa forma esta retornando bem. O comentário é mais por uma validação mesmo e segurança do que foi feito.

2020-12-16 15:53 UTC, matmsa27 commented on analytics_api/views.py
> +from django.db.models import Count, Q, Prefetch
A view ficou show, parabéns pelo job. Roda o black nesse arquivo também, no app de forma inteira também, acredito que tem alguns trechos fora do padrão do código do RP. No geral o PR tem alguns pontos de padrão código que merecem atenção e devem ser corrigidos. Senti falta dos testes também, é muito importante que os testes sejam desenvolvidos. Mas o código ta no caminho certo, só precisa corrigir esses pontos que mencionei.

2020-12-24 13:32 UTC, PeterAlexandre commented on analytics_api/README.md
> +**settings.py**
Esse arquivo foi apenas uma cópia do README dos outros apps. Somente seguimos o padrão do que estava feito.

2020-12-24 13:33 UTC, PeterAlexandre commented on analytics_api/README.md
> +from .settings_common import *
Esse arquivo foi apenas uma cópia do README dos outros apps. Somente seguimos o padrão do que estava feito.

2020-12-24 16:37 UTC, PeterAlexandre commented
Testes adicionados!

2021-01-08 18:26 UTC, jcbalmeida commented on analytics_api/views.py
> +from django.db.models import Count, Q, Prefetch
Dica: rode o black no mesmo padrão do rapidpro:
black --line-length=119 --target-version=py36

2021-01-11 21:36 UTC, PeterAlexandre commented on analytics_api/views.py
> +from django.db.models import Count, Q, Prefetch
Obrigado pela dica, @jcbalmeida.

Black aplicado: https://github.com/Ilhasoft/rapidpro-apps/pull/2/commits/8bc91a2412eee4b52aa2c7105fb0e0c3ac7c29dd

2021-01-12 00:24 UTC, jcbalmeida requested changes
O método filter_queryset não está coberto por testes.

2021-01-12 15:34 UTC, PeterAlexandre commented
Alterações sugeridas pelo @jcbalmeida foram adicionadas ao Pull Request. 

Serviu não só como correção, mas também conseguiu acentuar melhorias que podemos fazer no futuro, com os nossos testes.

2021-01-12 22:28 UTC, PeterAlexandre commented
@jcbalmeida, adicionei mais testes para cobrir totalmente o código.

```shell
Name    Stmts   Miss  Cover   Missing
-------------------------------------
-------------------------------------
TOTAL      45      0   100%

3 files skipped due to complete coverage.

```

2021-01-21 19:28 UTC, jcbalmeida approved these changes

2021-01-21 19:29 UTC, merged